//
// Generated by Bluespec Compiler (build 785e4e4)
//
// On Tue Nov  3 17:11:30 IST 2020
//
//
// Ports:
// Name                         I/O  size props
// fa_out                         O     2
// RDY_fa_out                     O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// fa_out_a                       I     1
// fa_out_b                       I     1
// fa_out_c_in                    I     1
//
// Combinational paths from inputs to outputs:
//   (fa_out_a, fa_out_b, fa_out_c_in) -> fa_out
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFA(CLK,
	    RST_N,

	    fa_out_a,
	    fa_out_b,
	    fa_out_c_in,
	    fa_out,
	    RDY_fa_out);
  input  CLK;
  input  RST_N;

  // value method fa_out
  input  fa_out_a;
  input  fa_out_b;
  input  fa_out_c_in;
  output [1 : 0] fa_out;
  output RDY_fa_out;

  // signals for module outputs
  wire [1 : 0] fa_out;
  wire RDY_fa_out;

  // remaining internal signals
  wire c_out__h21, s__h20, x__h33, x__h49, y__h34;

  // value method fa_out
  assign fa_out = { c_out__h21, s__h20 } ;
  assign RDY_fa_out = 1'd1 ;

  // remaining internal signals
  assign c_out__h21 = x__h33 | y__h34 ;
  assign s__h20 = x__h49 ^ fa_out_c_in ;
  assign x__h33 = fa_out_a & fa_out_b ;
  assign x__h49 = fa_out_a ^ fa_out_b ;
  assign y__h34 = fa_out_c_in & x__h49 ;
endmodule  // mkFA

